#!/bin/sh
#@ make-zapfdr -- script for creating the file zapfdr.ps
#@ Synopsis:
#@    $ make-zapfdr < ZapfDingbats.afm > zapfdr.ps
#
# Copyright (c) 2014 - 2018 Steffen (Daode) Nurpmeso <steffen@sdaoden.eu>.
#
# Copyright (C) 2006
# Free Software Foundation, Inc.
#      Written by Werner Lemberg <wl@gnu.org>
#
# This is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2, or (at your option) any later
# version.
#
# This is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with groff; see the file COPYING.  If not, write to the Free Software
# Foundation, 51 Franklin St - Fifth Floor, Boston, MA 02110-1301, USA.

# Write preamble.
cat <<END
%!PS-Adobe-3.0 Resource-Font
%%DocumentNeededResources: Font ZapfDingbats
%%EndComments
%%IncludeResource: Font ZapfDingbats

/ZapfDingbats findfont [-1 0 0 1 0 0] makefont

dup length 1 add dict begin
{
	exch dup dup /FID ne exch /UniqueID ne and {
		exch def
	} {
		pop pop
	} ifelse
} forall

/FontName /ZapfDingbats-Reverse def
END

# Emit reverse metrics.
sed '
  /^StartCharMetrics/ {
    s|StartCharMetrics \([0-9]*\)|/Metrics \1 dict dup begin|
    H
    d
  }

  /^C / {
    s|^.*$|&@|
    s|^.* N \([^ ]*\) ;.*$|&/\1 [|
    s|^.* B [0-9-]* [0-9-]* \([0-9]*\) [0-9-]* ;.*$|&-\1 |
    s|^.* B [0-9-]* [0-9-]* -\([0-9]*\) [0-9-]* ;.*$|&\1 |
    s|^.* WX \([0-9]*\) ;.*$|&-\1] def|
    s|^.* WX -\([0-9]*\) ;.*$|&\1] def|
    s|^.*@|	|
    H
    d
  }

  $ {
    g
    p
  }

  d
'

# Write postamble.
cat <<END

end def

/ZapfDingbats-Reverse currentdict end definefont pop
END

# s-sh-mode
